/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.hk.api;

import java.util.List;

import javax.validation.Valid;

import com.hk.model.Area;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


public interface AreaApi {

	@Operation(summary = "Add a new area to the database", description = "", tags = { "area" })
	@ApiResponses(value = {
			@ApiResponse(responseCode = "405", description = "Invalid input") })
	@RequestMapping(value = "/area/addArea",
			consumes = { "application/json" },
			method = RequestMethod.POST)
	ResponseEntity<Void> addArea(@Parameter(in = ParameterIn.DEFAULT, description = "Area object that needs to be added to the database", required = true, schema = @Schema()) @Valid @RequestBody Area body);


	@Operation(summary = "Returns all the priority areas", description = "Returns an array of priority A reas", tags = { "area" })
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "successful operation", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Area.class)))) })
	@RequestMapping(value = "/area/getAreas",
			produces = { "application/json" },
			method = RequestMethod.GET)
	ResponseEntity<List<Area>> getAreas();

}

