/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.hk.api;

import com.hk.model.User;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


public interface PriorityApi {

	@Operation(summary = "Creates a new priority", description = "", tags = { "priority" })
	@ApiResponses(value = {
			@ApiResponse(responseCode = "405", description = "Invalid input") })
	@RequestMapping(value = "/priority",
			consumes = { "application/json" },
			method = RequestMethod.POST)
	ResponseEntity<Void> addPriority(@Parameter(in = ParameterIn.DEFAULT, description = "Priority object that needs to be added to the database", required = true) @RequestBody User body);

}

