package com.hk.entity;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author Hilal Kaldane
 */
@Entity
public class AreaEntity implements Serializable {
	/**
	 * unique id to store priorityArea, it is autogenerated, so admin need not to pass areaId
	 * while adding new area into database
	 */
	@JsonProperty("areaId")
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long areaId;

	@JsonProperty("areaName")
	private String areaName = null;

	public Long getAreaId() {
		return areaId;
	}

	public void setAreaId(Long areaId) {
		this.areaId = areaId;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AreaEntity area = (AreaEntity) o;
		return Objects.equals(this.areaId, area.areaId) &&
				Objects.equals(this.areaName, area.areaName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(areaId, areaName);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Area {\n");

		sb.append("    areaId: ").append(toIndentedString(areaId)).append("\n");
		sb.append("    areaName: ").append(toIndentedString(areaName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
